[build]
  command = "npm run build"
  publish = "public"
  functions = "BANORANT/netlify/functions"

[functions]
  directory = "BANORANT/netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 